name: Construcción de imagen y despliegue con Docker en EC2

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Construir imagen de Docker y desplegar en EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/isa-abr26-cicd-docker:flaskapp

      - name: Deployment EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            sudo systemctl stop httpd || true

            sudo docker image pull ${{ secrets.DOCKER_USERNAME }}/isa-abr26-cicd-docker:flaskapp

            sudo docker container stop contflaskmateo || true
            sudo docker container rm contflaskmateo || true

            sudo docker container stop app-isa || true
            sudo docker container rm app-isa || true

            sudo docker container run -d --name contflaskmateo -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/isa-abr26-cicd-docker:flaskapp

            sudo docker ps
